plugins:
  - jekyll-paginate
  - jekyll-archives

author: Tesser

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categories/:name/'

defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      image: /preview.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Tessera"
      image: /preview.jpg
  -
    scope:
      path: ""
      type: "chapters"
    values:
      image: /preview.jpg
      
collections:
  chapters:
    output: true
    permalink: /:name/      
    
paginate: 9
paginate_path: "/page:num/"

date_format: "%d/%m/%Y"
